all:
	gcc -g -c main.c 
	gcc -g -c matriz_esparsa.c
	gcc -g -c vetor_esparso.c 
	gcc -g -c THEA.c
	gcc -g -c testes_TAD.c
	gcc -g -c matriz_densa.c
	gcc -g -c vetor_dinamico.c
	gcc -g -c lista_encadeada.c
	gcc -o main main.o lista_encadeada.o vetor_dinamico.o matriz_densa.o testes_TAD.o THEA.o matriz_esparsa.o vetor_esparso.o
# ./main
# del *.exe
# del *.o
# rm *.exe
# rm *.o